//////////////////////////////////////////////////////////////////////
//                                                                  //
//    ██████╗ ███████╗ █████╗  ██████╗████████╗ ██████╗ ██████╗     //
//    ██╔══██╗██╔════╝██╔══██╗██╔════╝╚══██╔══╝██╔═══██╗██╔══██╗    //
//    ██████╔╝█████╗  ███████║██║        ██║   ██║   ██║██████╔╝    //
//    ██╔══██╗██╔══╝  ██╔══██║██║        ██║   ██║   ██║██╔══██╗    //
//    ██║  ██║███████╗██║  ██║╚██████╗   ██║   ╚██████╔╝██║  ██║    //
//    ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝    //
//                                                                  //
//                         A FALLOUT4 ENB                           //
//                                                                  //
///// MOD PAGE ///////////////////////////////////////////////////////
//                                                                  //
//    https://www.nexusmods.com/fallout4/mods/57321                 //
//                                                                  //
//////////////////////////////////////////////////////////////////////
//                                                                  //
//                            S E T U P                             //
//                                                                  //
//////////////////////////////////////////////////////////////////////

#define VERSION_NUMBER          "1.7.0"

///// enbeffect.fx ///////////////////////////////////////////////////

#define E_TONEMAPPER            1       //  [1-3]   Choose TONEMAPPER // 1 = UNCHARTED II / 2 = ACES FITTED / 3 = FALLOUT4 VANILLA
#define E_TONEMAPPER_MODE       0       //  [0-1]   Choose TONEMAPPER MODE // 0 = IMAGE SPACE / 1 = MANUAL
#define E_COLORSPACE            4       //  [0-4]   Choose COLORSPACE // 0 = VANILLA / 1 = EMISSIVE LIGHTS / 2 = ACES / 3 = AGX / 4 = AWG
#define E_ADAPTATION            3       //  [1-3]   Choose ADAPTATION mode // 1 = ENB / 2 = VANILLA / 3 = VANILLA AUTO EXPOSURE
#define E_ADAPTTOOL             0       //  [0-1]   Enables ADAPTATION level visualization // 0 = Disable / 1 = Enable
#define E_DITHERING             1       //  [0-1]   Enables dither // 0 = Disable / 1 = Enable

///// enbpostpass.fx /////////////////////////////////////////////////

#define E_CUSTOM_LUTS           0       //  [0-1]   This option allows to use 8 CUSTOM LUT files // 0 = Disable / 1 = Enable 
#define E_ADVANCED_GRAIN        0       //  [0-1]   Advanced UI settings for FILM GRAIN // 0 = Disable / 1 = Enable 
#define E_ADVANCED_CA           0       //  [0-1]   Advanced UI settings for CHROMATIC ABERRATION // 0 = Disable / 1 = Enable 
#define E_ADVANCED_GLITCH       0       //  [0-1]   Advanced UI settings for RGB GLITCH // 0 = Disable / 1 = Enable 

////// enbdepthoffield.fx ////////////////////////////////////////////

#define E_OPTICAL_VIGNETTE      1       //  [0-1]   Enables partial occlusion of bokeh disc at screen corners // 0 = Disable / 1 = Enable 
#define E_CHROMATIC_ABERRATION  1       //  [0-1]   Enables chromatic aberration at bokeh shape borders // 0 = Disable / 1 = Enable 

////// weather id according to _weatherlist.ini [WEATHER###] /////////

#define RAIN_START              32      //  Initial ID of the rainy weather category
#define RAIN_ENDS               37      //  End ID of the rainy weather category
#define STORM_START             38      //  Initial ID of the storm weather category
#define STORM_ENDS              42      //  End ID of the storm weather category

//////////////////////////////////////////////////////////////////////